### ISSUE TITLE
Division of two fractions

### ISSUE THREAD

**Issue by alexph9** [alexph9/IWVG.SwC.Alejandro.Puebla.Holguin#6]
Divide dos fracciones y te da el resultado.
[Ver la wiki!](../wiki/IWVG.SwC.Alejandro.Puebla.Holguin#public-fraction-divisionfraction-fraction)

**Comment by manupuchades** [comment]
El lunes por la tarde/noche estará lista

**Comment by alexph9** [comment]
Genial @manupuchades, muchas gracias!

**Comment by manupuchades** [comment]
Terminado código + test unitario
